### ISSUE TITLE
 Upstream model implementation to vLLM

### ISSUE THREAD

**Issue by ywang96** [rhymes-ai/Aria#20]
Hello! This is Roger from the vLLM team!

It's great to see you are using the OOT model registration functionality to have this model supported on vLLM! Do you plan to make a PR in the upstream repository so that we can have this model officially supported?

If you don't have the bandwidth to make a PR, I'm happy to make it and put relevant team members as co authors - Let me know!

**Comment by xffxff** [comment]
I'm working on this. I've submitted a pull request https://github.com/vllm-project/vllm/pull/10514
