### ISSUE TITLE
Reading PDF files

### ISSUE THREAD

**Issue by andy8025** [rhymes-ai/Aria#25]
Hi, your blog (in the section titled Long Multimodal Input - Paper Reading) shows an example of Aria answering a question based on a PDF file. https://www.rhymes.ai/blog-details/aria-first-open-multimodal-native-moe-model   However, when I feed the same PDF file into Aria running locally it outputs "PIL.UnidentifiedImageError: cannot identify image file 'test.pdf'"  Does Aria natively support PDF files as input? Am I just not using the right Python library (PIL)? Thanks.

**Comment by aria-hacker** [comment]
No, the raw inputs for Aria model support image and text only. For the PDF files, you have to preprocess it with `PyMUPDF` library. [Here](https://github.com/rhymes-ai/Aria/blob/09ee22a83fddb60d8e88bedc4234af656fc95468/inference/notebooks/03_multipage_pdf_understanding.ipynb) are some more details that how to process PDF files. @andy8025
