### ISSUE TITLE
Train OOM

### ISSUE THREAD

**Issue by luyao-cv** [rhymes-ai/Aria#38]
i have 8 A100 (80GB) GPUs.
i want to do Full parameter fine-tuning
`
accelerate launch --config_file recipes/accelerate_configs/zero2.yaml aria/train.py --config recipes/config_full.yaml
`
this instruct lead to OOM.

**Comment by Coobiw** [comment]
Hi, you can `git pull` the latest code and set `max_seq_length` lower. If the issue persists, consider using more memory-efficient strategies such as [ZERO3](https://github.com/rhymes-ai/Aria/blob/main/recipes/accelerate_configs/zero3.yaml) or [ZERO3-Offload](https://github.com/rhymes-ai/Aria/blob/main/recipes/accelerate_configs/zero3_offload_param.yaml).

**Comment by luyao-cv** [comment]
OK, I trained successfully. Thank you
