### ISSUE TITLE
report vllm example bug

### ISSUE THREAD

**Issue by zwc163** [rhymes-ai/Aria#44]
aria/aria.py", line 1054, in input_processor
[rank0]:     new_prompt, new_token_ids = repeat_and_pad_placeholder_tokens(
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/multimodal/utils.py", line 231, in repeat_and_pad_placeholder_tokens
[rank0]:     replacement_ids = repeat_and_pad_token(
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/multimodal/utils.py", line 178, in repeat_and_pad_token
[rank0]:     replacement = [token] * repeat_count
[rank0]: TypeError: can't multiply sequence by non-int of type 'list'

**Comment by aria-hacker** [comment]
Which vLLM version are you trying with? For the current implementation, we just test it with v.0.6.2.

**Comment by zwc163** [comment]
thank you
