### ISSUE TITLE
can you open source pretrained model for futher finetuning?

### ISSUE THREAD

**Issue by runvyang** [rhymes-ai/Aria#48]
I would like to enhance some of the fundamental  ability such as captioning/reasoning, i would like the ability to do continue training, hence a pretrained model is required, also, to extent the modality to audio, i think a pretrained model is needed, thank you.

**Comment by Martins6** [comment]
Hey, @runvyang , they've provided the weights on HuggingFace, check it out!

https://huggingface.co/rhymes-ai/Aria

**Comment by maazel-rhymes** [comment]
> I would like to enhance some of the fundamental ability such as captioning/reasoning, i would like the ability to do continue training, hence a pretrained model is required, also, to extent the modality to audio, i think a pretrained model is needed, thank you.

Updated Aria on the way, we will consider your proposal. Thanks!

**Comment by xffxff** [comment]
We have released the base models (with native multimodal pre-training) for Aria ([Aria-Base-8K](https://huggingface.co/rhymes-ai/Aria-Base-8K) and [Aria-Base-64K](https://huggingface.co/rhymes-ai/Aria-Base-64K))
