### ISSUE TITLE
How to run Aria + LoRA with vLLM?

### ISSUE THREAD

**Issue by thanhnguyentung95** [rhymes-ai/Aria#57]
Thanks for make this amazing project open. I’m finetuning Aria to create a LoRA. But then I can not serve the resulted model with vLLM. Here are two appoaches I have tried:

1. Enable LoRA with vLLM => LoRA not supported for Aria
2. Try to merge LoRA with base model => the merge method IsNotImplemented

Any ideas to serve fine-tuned Aria with vLLM?

**Comment by xffxff** [comment]
Hi @thanhnguyentung95 
Thank you for your interest in the project and for working on fine-tuning Aria! Currently, we don't have plans to support LoRA integration with vLLM in the near future. However, we'd definitely welcome contributions if anyone is interested in working on it.

**Comment by thanhnguyentung95** [comment]
Hi @xffxff 
I'm investigating this. I will make a PR when it's done.

**Comment by leon-seidel** [comment]
Hi @thanhnguyentung95,
is there an example for how to merge a LoRA adapter with the base model?
