### ISSUE TITLE
How to implement ViT using eager mode?

### ISSUE THREAD

**Issue by DeadLining** [rhymes-ai/Aria#87]
I modified `_attn_implementation` in the `config.json` file, but it doesn't work.

`"vision_config": {
    "_flash_attn_2_enabled": true,
    "_attn_implementation": "flash_attention_2",
}`

**Comment by xffxff** [comment]
Try this

```python
model = AutoModelForCausalLM.from_pretrained(
    model_id_or_path, 
    device_map="auto", 
    torch_dtype=torch.bfloat16, 
    trust_remote_code=True, 
    attn_implementation="eager"
```
